openapi: 3.0.0
info:
  title: spurdo
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8000/
    description: Local host server
paths:
  ...
components:
  schemas:
    ...
  securitySchemes:
    ...